name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main   # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: whymeuno   # 你在 Cloudflare Pages 上创建的项目名
          directory: site/            # 因为你是纯静态页面，直接指定仓库根目录
